# Generated by Django 3.1.4 on 2020-12-23 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab8', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='base',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='База'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='chassis',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Шасси'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='engine',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Мотор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='head',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Руководитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
